"""Build models/cart_pbpk_pd_singh2020.cpp from the paper's own model code.

Usage: python tools/build_cart_pbpk.py <kmab-12-01-1688616-s001.docx>

The Supplementary Material of Singh AP, Zheng X, Lin-Schmidt X, Chen W,
Carpenter TJ, Zong A, Wang W, Heald DL, "Development of a quantitative
relationship between CAR-affinity, antigen abundance, tumor cell depletion and
CAR-T cell expansion using a multiscale systems PK-PD model", mAbs
2020;12:1688616 (open access), contains the MLXTRAN source of the PBPK-PD
model and the estimates it was run with. This reads that source out of the
.docx and rewrites it as an mrgsolve model file, so the transcription is
mechanical and can be re-checked against the paper.

Differences from the MLXTRAN source, all of form rather than content:
- kon, koff, the antigen density and the initial tumour volume are given in
  MLXTRAN as doses into states with a zero derivative; here they are ordinary
  parameters, and the tumour volume is a compartment with an initial value.
- Local quantities that depend on a state (the tumour's vascular and
  extravascular volumes, complexes per cell, the rate functions) are computed
  inside $ODE, and again in $TABLE for the outputs.
"""
import re
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'models' / 'cart_pbpk_pd_singh2020.cpp'

# Parameters the MLXTRAN file receives as "doses" or fits, with the values of
# the anti-BCMA CAR-T / RPMI-8226 run in the Supplementary Material
INPUTS = [
    ('KON', 1.08e-12, 'Association rate constant, CAR-TAA (1/(cells/mL)/h)'),
    ('KOFF', 6.48, 'Dissociation rate constant, CAR-TAA (1/h)'),
    ('DENSITY_TAA', 12590.0, 'Tumour-associated antigen per tumour cell (number/cell)'),
    ('DENSITY_CAR', 5000.0, 'CAR molecules per CAR-T cell (number/cell)'),
    ('VTUMOR0', 0.05, 'Tumour volume at the start (mL)'),
    ('TARGETCELL', 1e8, 'Tumour cells per mL of tumour (cells/mL)'),
    ('KG_EXP_TUMOR', 0.00305, 'Exponential tumour growth rate (1/h)'),
    ('KKILL_MAX', 0.0486, 'Maximum killing rate of tumour cells (1/h)'),
    ('IC50', 9.94, 'Complexes per tumour cell for half-maximal killing (number/cell)'),
    ('KEXP_CART_MAX', 0.0906, 'Maximum CAR-T expansion rate in the tumour (1/h)'),
    ('EC50', 5.18, 'Complexes per tumour cell for half-maximal expansion (number/cell)'),
    ('TAU_KILL', 21.6, 'Mean transit time of the killing delay (h)'),
    ('GAMMA_ACT', 1.0, 'Hill coefficient, expansion (-)'),
    ('GAMMA_KILL', 1.0, 'Hill coefficient, killing (-)'),
]
DESCRIPTIONS = {
    'Q_': 'Blood flow', 'L_': 'Lymph flow', 'V_': 'Volume', 'J_': 'Transmigration rate',
}
UNITS = {'Q_': 'mL/h', 'L_': 'mL/h', 'V_': 'mL', 'J_': '1/h'}
# assignments this script writes itself, in $ODE and again in $TABLE
REWRITTEN = {'TargetCell', 'CplxPCART', 'CplxPT', 'Kact_CART', 'Kkill',
             'OutputVolume', 'OutputCART', 'output'}
ORGAN = {'Lung': 'lung', 'Spleen': 'spleen', 'GI': 'gut', 'Liver': 'liver', 'Kidney': 'kidney',
         'Brain': 'brain', 'Tumor': 'tumour', 'Other': 'the rest of the body', 'Blood': 'blood',
         'LN': 'the lymph node'}

HEADER = '''$PROB
CAR-T cells: whole-body PBPK with tumour binding, expansion and killing (mouse)

// {cite}
//
// PRECLINICAL MODEL, MOUSE PARAMETERS. A 25 g immunodeficient mouse carrying a
// xenograft; the defaults are the anti-BCMA CAR-T run against RPMI-8226
// multiple myeloma cells. Not a human model.
//
// GENERATED by tools/build_cart_pbpk.py from the MLXTRAN model code in the
// paper's Supplementary Material. Do not edit by hand.
//
// Where the cells go: CAR-T cells follow blood flow (Q) through lung, spleen,
// gut, liver, kidney, brain, tumour and the rest of the body. Each organ has a
// vascular and an extravascular space; cells cross into tissue at a
// first-order rate (J), drain back through lymph (L) into a lymph-node
// compartment and return to blood. Gut and spleen drain through the liver,
// where cells are also lost (Kdep_Liver).
//
// What they do: in the tumour, CAR molecules bind tumour antigen to form
// CAR-target complexes (kon, koff). Complexes per tumour cell drive CAR-T
// expansion and tumour-cell killing, each a Hill function; killing acts
// through a chain of four transit compartments, so the effect on tumour volume
// lags the binding. The tumour otherwise grows exponentially.
//
// Units: time h, concentrations cells/mL, tumour volume mL (1 mL = 1e8 tumour
// cells), complexes per mL of tumour interstitium. Dose CAR-T cells into
// C_Blood as cells divided by the blood volume (0.944 mL).
'''
CITE = ('Singh AP, Zheng X, Lin-Schmidt X, Chen W, Carpenter TJ, Zong A, Wang W, Heald DL. Development of '
        'a quantitative\n// relationship between CAR-affinity, antigen abundance, tumor cell depletion and '
        'CAR-T cell expansion\n// using a multiscale systems PK-PD model. mAbs 2020;12:1688616 (open access).')


def mlxtran_source(docx):
    """The model code block from the .docx, as lines."""
    x = zipfile.ZipFile(docx).read('word/document.xml').decode('utf8')
    paras = re.findall(r'<w:p[ >].*?</w:p>', x, re.S)
    text = [''.join(re.findall(r'<w:t[^>]*>([^<]*)</w:t>', p)) for p in paras]
    text = [t.replace('&lt;', '<').replace('&gt;', '>').replace('&amp;', '&') for t in text]
    start = next(i for i, t in enumerate(text) if t.startswith('A MLXTRAN model code file'))
    return [t.rstrip() for t in text[start + 1:] if t.strip()]


def strip_comment(line):
    return line.split(';')[0].strip()


def main(docx):
    src = mlxtran_source(docx)
    consts, odes, inits, locals_ = {}, [], {}, []
    for raw in src:
        line = strip_comment(raw)
        if not line or line.startswith(('[', 'input=', 'PK:', 'EQUATION:', 'OUTPUT:', 'odeType', 'depot(')):
            continue
        m = re.match(r'ddt_(\w+)\s*=\s*(.+)$', line)
        if m:
            odes.append((m.group(1), m.group(2)))
            continue
        m = re.match(r'(\w+)_0\s*=\s*(.+)$', line)
        if m:
            inits[m.group(1)] = m.group(2)
            continue
        m = re.match(r'(\w+)\s*=\s*(.+)$', line)
        if m:
            name, expr = m.group(1), m.group(2)
            if name in REWRITTEN:
                continue
            try:
                consts[name] = float(expr)
            except ValueError:
                locals_.append((name, expr))
    states = [s for s, _ in odes if s not in ('kon', 'koff', 'Density_TAA', 'route')]
    fixed = {k: v for k, v in consts.items() if not k.startswith(('TargetCell',))}

    L = [HEADER.format(cite=CITE), '$PARAM @annotated']
    for k, v, d in INPUTS:
        L.append('%-13s : %-11g : %s' % (k, v, d))
    for k in sorted(fixed, key=lambda s: (s[:2], s)):
        pre = k[:2]
        organ = k.split('_', 1)[1] if '_' in k else k
        organ = ORGAN.get(organ.replace('_v', '').replace('_e', ''), organ)
        space = ', vascular' if k.endswith('_v') else (', extravascular' if k.endswith('_e') else '')
        if k.startswith('FR_'):
            note = 'Fraction of lymph flow returning from %s (-)' % ORGAN.get(k[3:], k[3:])
        elif k.startswith('Kdep_'):
            note = 'First-order loss of CAR-T cells in the %s (1/h)' % ORGAN.get(k[5:], k[5:])
        else:
            note = '%s, %s%s (%s)' % (DESCRIPTIONS.get(pre, k), organ, space, UNITS.get(pre, '-'))
        L.append('%-13s : %-11g : %s' % (k, fixed[k], note))

    L.append('\n$CMT @annotated')
    for s in states:
        if s == 'V_Tumor':
            L.append('%-11s : Tumour volume (mL)' % s)
        elif s == 'TE':
            L.append('%-11s : CAR-target complexes in the tumour interstitium (number/mL)' % s)
        elif s == 'A_E_Tumor':
            L.append('%-11s : CAR-T cells in the tumour interstitium (cells)' % s)
        elif s.startswith('K') and len(s) == 2:
            L.append('%-11s : Killing-delay transit compartment %s (1/h)' % (s, s[1]))
        else:
            kind = 'vascular' if '_V_' in s else ('extravascular' if '_E_' in s else 'blood')
            organ = ORGAN.get(s.split('_')[-1], s)
            L.append('%-11s : CAR-T cells in the %s space of %s (cells/mL)' % (s, kind, organ)
                     if '_' in s[2:] else '%-11s : CAR-T cells in %s (cells/mL)' % (s, organ))

    L.append('\n$MAIN')
    L.append('V_Tumor_0 = VTUMOR0;')
    L.append('A_E_Tumor_0 = %s;' % inits.get('A_E_Tumor', '1E-10'))

    def rewrite(expr):
        expr = expr.replace('Density_CAR', 'DENSITY_CAR').replace('Density_TAA', 'DENSITY_TAA')
        expr = expr.replace('TargetCell', 'TARGETCELL').replace('kon', 'KON').replace('koff', 'KOFF')
        expr = re.sub(r'\bKexp_CART_max\b', 'KEXP_CART_MAX', expr)
        expr = re.sub(r'\bKkill_max\b', 'KKILL_MAX', expr)
        expr = re.sub(r'\bKg_Exp_Tumor\b', 'KG_EXP_TUMOR', expr)
        expr = re.sub(r'\btau_kill\b', 'TAU_KILL', expr)
        expr = re.sub(r'\bgamma_act\b', 'GAMMA_ACT', expr)
        expr = re.sub(r'\bgamma_kill\b', 'GAMMA_KILL', expr)
        expr = re.sub(r'\bEC50\b', 'EC50', expr)
        expr = re.sub(r'\(([^()]+)\)\^([A-Za-z_0-9]+)', r'pow(\1, \2)', expr)
        return re.sub(r'\s+', ' ', expr).strip()

    # locals that depend on a state, in dependency order, then the ODEs
    dyn = [(n, rewrite(e)) for n, e in locals_]
    body = ['double %s = %s;' % (n, e) for n, e in dyn]
    body += ['double CplxPCART = TE * V_Tumor_e / A_E_Tumor;',
             'double CplxPT = TE / TARGETCELL;',
             'double Kact_CART = KEXP_CART_MAX * pow(CplxPT, GAMMA_ACT) / (pow(CplxPT, GAMMA_ACT) + pow(EC50, GAMMA_ACT));',
             'double Kkill = KKILL_MAX * pow(CplxPT, GAMMA_KILL) / (pow(CplxPT, GAMMA_KILL) + pow(IC50, GAMMA_KILL));']
    L.append('\n$ODE')
    L += body
    for s, e in odes:
        if s in ('kon', 'koff', 'Density_TAA', 'route'):
            continue
        L.append('dxdt_%s = %s;' % (s, rewrite(e)))

    # mrgsolve declares captured variables once, so $TABLE only assigns them
    L.append('\n$TABLE')
    L += [re.sub(r'^double ', '', b) for b in body]
    L.append('double TumorVolume = V_Tumor > 0 ? V_Tumor * 1000 : 0;   // mm3')
    L.append('double CARTblood = C_Blood / 1000;                       // cells per uL')
    L.append('double CARTtumor = A_E_Tumor / V_Tumor_e;                // cells per mL of tumour')
    L.append('\n$CAPTURE TumorVolume CARTblood CARTtumor CplxPT CplxPCART Kkill Kact_CART')
    with open(OUT, 'w', newline='\n') as f:
        f.write('\n'.join(L) + '\n')
    print(len(states), 'states,', len(fixed), 'physiological parameters ->', OUT.name)


if __name__ == '__main__':
    main(sys.argv[1])
