$PROB
CAR-T cells: whole-body PBPK with tumour binding, expansion and killing (mouse)

// Singh AP, Zheng X, Lin-Schmidt X, Chen W, Carpenter TJ, Zong A, Wang W, Heald DL. Development of a quantitative
// relationship between CAR-affinity, antigen abundance, tumor cell depletion and CAR-T cell expansion
// using a multiscale systems PK-PD model. mAbs 2020;12:1688616 (open access).
//
// PRECLINICAL MODEL, MOUSE PARAMETERS. A 25 g immunodeficient mouse carrying a
// xenograft; the defaults are the anti-BCMA CAR-T run against RPMI-8226
// multiple myeloma cells. Not a human model.
//
// GENERATED by tools/build_cart_pbpk.py from the MLXTRAN model code in the
// paper's Supplementary Material. Do not edit by hand.
//
// Where the cells go: CAR-T cells follow blood flow (Q) through lung, spleen,
// gut, liver, kidney, brain, tumour and the rest of the body. Each organ has a
// vascular and an extravascular space; cells cross into tissue at a
// first-order rate (J), drain back through lymph (L) into a lymph-node
// compartment and return to blood. Gut and spleen drain through the liver,
// where cells are also lost (Kdep_Liver).
//
// What they do: in the tumour, CAR molecules bind tumour antigen to form
// CAR-target complexes (kon, koff). Complexes per tumour cell drive CAR-T
// expansion and tumour-cell killing, each a Hill function; killing acts
// through a chain of four transit compartments, so the effect on tumour volume
// lags the binding. The tumour otherwise grows exponentially.
//
// Units: time h, concentrations cells/mL, tumour volume mL (1 mL = 1e8 tumour
// cells), complexes per mL of tumour interstitium. Dose CAR-T cells into
// C_Blood as cells divided by the blood volume (0.944 mL).

$PARAM @annotated
KON           : 1.08e-12    : Association rate constant, CAR-TAA (1/(cells/mL)/h)
KOFF          : 6.48        : Dissociation rate constant, CAR-TAA (1/h)
DENSITY_TAA   : 12590       : Tumour-associated antigen per tumour cell (number/cell)
DENSITY_CAR   : 5000        : CAR molecules per CAR-T cell (number/cell)
VTUMOR0       : 0.05        : Tumour volume at the start (mL)
TARGETCELL    : 1e+08       : Tumour cells per mL of tumour (cells/mL)
KG_EXP_TUMOR  : 0.00305     : Exponential tumour growth rate (1/h)
KKILL_MAX     : 0.0486      : Maximum killing rate of tumour cells (1/h)
IC50          : 9.94        : Complexes per tumour cell for half-maximal killing (number/cell)
KEXP_CART_MAX : 0.0906      : Maximum CAR-T expansion rate in the tumour (1/h)
EC50          : 5.18        : Complexes per tumour cell for half-maximal expansion (number/cell)
TAU_KILL      : 21.6        : Mean transit time of the killing delay (h)
GAMMA_ACT     : 1           : Hill coefficient, expansion (-)
GAMMA_KILL    : 1           : Hill coefficient, killing (-)
Density_CAR   : 5000        : Density_CAR, CAR (-)
FR_LN         : 1           : Fraction of lymph flow returning from the lymph node (-)
FR_Spleen     : 1           : Fraction of lymph flow returning from spleen (-)
J_Brain       : 1.4         : Transmigration rate, brain (1/h)
J_GI          : 9.05        : Transmigration rate, gut (1/h)
J_Kidney      : 296.75      : Transmigration rate, kidney (1/h)
J_Liver       : 716.49      : Transmigration rate, liver (1/h)
J_Lung        : 4705.13     : Transmigration rate, lung (1/h)
J_Other       : 86.8        : Transmigration rate, the rest of the body (1/h)
J_Spleen      : 1799.76     : Transmigration rate, spleen (1/h)
J_Tumor       : 10.35       : Transmigration rate, tumour (1/h)
Kdep_Liver    : 0.0288      : First-order loss of CAR-T cells in the liver (1/h)
L_Brain       : 0.00236     : Lymph flow, brain (mL/h)
L_GI          : 0.0151      : Lymph flow, gut (mL/h)
L_Kidney      : 0.0137      : Lymph flow, kidney (mL/h)
L_LN          : 0.14926     : Lymph flow, the lymph node (mL/h)
L_Liver       : 0.00206     : Lymph flow, liver (mL/h)
L_Lung        : 0.0746      : Lymph flow, lung (mL/h)
L_Other       : 0.0386      : Lymph flow, the rest of the body (mL/h)
L_Spleen      : 0.00164     : Lymph flow, spleen (mL/h)
L_Tumor       : 0.0012      : Lymph flow, tumour (mL/h)
Q_Brain       : 11.8        : Blood flow, brain (mL/h)
Q_GI          : 75.4        : Blood flow, gut (mL/h)
Q_Kidney      : 68.5        : Blood flow, kidney (mL/h)
Q_Liver       : 10.3        : Blood flow, liver (mL/h)
Q_Lung        : 373         : Blood flow, lung (mL/h)
Q_Other       : 192.82      : Blood flow, the rest of the body (mL/h)
Q_Spleen      : 8.18        : Blood flow, spleen (mL/h)
Q_Tumor       : 6           : Blood flow, tumour (mL/h)
V_Blood       : 0.944       : Volume, blood (mL)
V_Brain_e     : 0.0873      : Volume, brain, extravascular (mL)
V_Brain_v     : 0.0107      : Volume, brain, vascular (mL)
V_GI_e        : 0.1815      : Volume, gut, extravascular (mL)
V_GI_v        : 0.0166      : Volume, gut, vascular (mL)
V_Kidney_e    : 0.0788      : Volume, kidney, extravascular (mL)
V_Kidney_v    : 0.0289      : Volume, kidney, vascular (mL)
V_LN          : 0.113       : Volume, the lymph node (mL)
V_Liver_e     : 0.385       : Volume, liver, extravascular (mL)
V_Liver_v     : 0.164       : Volume, liver, vascular (mL)
V_Lung_e      : 0.0384      : Volume, lung, extravascular (mL)
V_Lung_v      : 0.0295      : Volume, lung, vascular (mL)
V_Other_e     : 4.11183     : Volume, the rest of the body, extravascular (mL)
V_Other_v     : 0.55209     : Volume, the rest of the body, vascular (mL)
V_Spleen_e    : 0.0254      : Volume, spleen, extravascular (mL)
V_Spleen_v    : 0.0154      : Volume, spleen, vascular (mL)

$CMT @annotated
C_Blood     : CAR-T cells in blood (cells/mL)
C_V_Lung    : CAR-T cells in the vascular space of lung (cells/mL)
C_E_Lung    : CAR-T cells in the extravascular space of lung (cells/mL)
C_V_Spleen  : CAR-T cells in the vascular space of spleen (cells/mL)
C_E_Spleen  : CAR-T cells in the extravascular space of spleen (cells/mL)
C_V_Kidney  : CAR-T cells in the vascular space of kidney (cells/mL)
C_E_Kidney  : CAR-T cells in the extravascular space of kidney (cells/mL)
C_V_Brain   : CAR-T cells in the vascular space of brain (cells/mL)
C_E_Brain   : CAR-T cells in the extravascular space of brain (cells/mL)
C_V_Other   : CAR-T cells in the vascular space of the rest of the body (cells/mL)
C_E_Other   : CAR-T cells in the extravascular space of the rest of the body (cells/mL)
C_V_GI      : CAR-T cells in the vascular space of gut (cells/mL)
C_E_GI      : CAR-T cells in the extravascular space of gut (cells/mL)
C_V_Liver   : CAR-T cells in the vascular space of liver (cells/mL)
C_E_Liver   : CAR-T cells in the extravascular space of liver (cells/mL)
C_LN        : CAR-T cells in the lymph node (cells/mL)
C_V_Tumor   : CAR-T cells in the vascular space of tumour (cells/mL)
K1          : Killing-delay transit compartment 1 (1/h)
K2          : Killing-delay transit compartment 2 (1/h)
K3          : Killing-delay transit compartment 3 (1/h)
K4          : Killing-delay transit compartment 4 (1/h)
TE          : CAR-target complexes in the tumour interstitium (number/mL)
A_E_Tumor   : CAR-T cells in the tumour interstitium (cells)
V_Tumor     : Tumour volume (mL)

$MAIN
V_Tumor_0 = VTUMOR0;
A_E_Tumor_0 = 1E-10;

$ODE
double V_Tumor_v = 0.113* V_Tumor;
double V_Tumor_e = 0.887* V_Tumor;
double CplxPCART = TE * V_Tumor_e / A_E_Tumor;
double CplxPT = TE / TARGETCELL;
double Kact_CART = KEXP_CART_MAX * pow(CplxPT, GAMMA_ACT) / (pow(CplxPT, GAMMA_ACT) + pow(EC50, GAMMA_ACT));
double Kkill = KKILL_MAX * pow(CplxPT, GAMMA_KILL) / (pow(CplxPT, GAMMA_KILL) + pow(IC50, GAMMA_KILL));
dxdt_C_Blood = (-(Q_Lung+L_Lung)*C_Blood + (Q_GI-L_GI+Q_Spleen-L_Spleen +Q_Liver-L_Liver)*C_V_Liver + (Q_Kidney-L_Kidney)*C_V_Kidney + (Q_Brain-L_Brain)*C_V_Brain+ L_LN*FR_LN*C_LN+ (Q_Other-L_Other)*C_V_Other + (Q_Tumor-L_Tumor)*C_V_Tumor)/V_Blood;
dxdt_C_V_Lung = ((Q_Lung+L_Lung)*C_Blood - J_Lung*C_V_Lung*V_Lung_v - Q_Lung*C_V_Lung)/V_Lung_v;
dxdt_C_E_Lung = (J_Lung*C_V_Lung*V_Lung_v - L_Lung*C_E_Lung)/V_Lung_e;
dxdt_C_V_Spleen = (Q_Spleen*C_V_Lung - J_Spleen*C_V_Spleen*V_Spleen_v - (Q_Spleen-L_Spleen)*C_V_Spleen)/V_Spleen_v;
dxdt_C_E_Spleen = (J_Spleen*C_V_Spleen*V_Spleen_v - L_Spleen*C_E_Spleen)/V_Spleen_e;
dxdt_C_V_Kidney = (Q_Kidney*C_V_Lung - J_Kidney*C_V_Kidney*V_Kidney_v - (Q_Kidney-L_Kidney)*C_V_Kidney)/V_Kidney_v;
dxdt_C_E_Kidney = (J_Kidney*C_V_Kidney*V_Kidney_v - L_Kidney*C_E_Kidney)/V_Kidney_e;
dxdt_C_V_Brain = (Q_Brain*C_V_Lung - J_Brain*C_V_Brain*V_Brain_v - (Q_Brain-L_Brain)*C_V_Brain)/V_Brain_v;
dxdt_C_E_Brain = (J_Brain*C_V_Brain*V_Brain_v - L_Brain*C_E_Brain)/V_Brain_e;
dxdt_C_V_Other = (Q_Other*C_V_Lung - J_Other*C_V_Other*V_Other_v - (Q_Other-L_Other)*C_V_Other)/V_Other_v;
dxdt_C_E_Other = (J_Other*C_V_Other*V_Other_v - L_Other*C_E_Other)/V_Other_e;
dxdt_C_V_GI = (Q_GI*C_V_Lung - J_GI*C_V_GI*V_GI_v - (Q_GI-L_GI)*C_V_GI )/V_GI_v;
dxdt_C_E_GI = (J_GI*C_V_GI*V_GI_v - L_GI*C_E_GI)/V_GI_e;
dxdt_C_V_Liver = (Q_Liver*C_V_Lung - J_Liver*C_V_Liver*V_Liver_v -(Q_GI-L_GI+Q_Spleen-L_Spleen +Q_Liver-L_Liver)*C_V_Liver + (Q_GI-L_GI)*C_V_GI + (Q_Spleen-L_Spleen)*C_V_Spleen)/V_Liver_v;
dxdt_C_E_Liver = (J_Liver*C_V_Liver*V_Liver_v - L_Liver*C_E_Liver)/V_Liver_e - Kdep_Liver * C_E_Liver;
dxdt_C_LN = (L_Liver*C_E_Liver + L_GI*C_E_GI + L_Tumor*(A_E_Tumor/V_Tumor_e - TE/DENSITY_CAR) + L_Other*C_E_Other + L_Brain*C_E_Brain + L_Kidney*C_E_Kidney + L_Spleen*C_E_Spleen*FR_Spleen + L_Lung*C_E_Lung - L_LN*FR_LN*C_LN)/V_LN;
dxdt_C_V_Tumor = (Q_Tumor*C_V_Lung - J_Tumor*C_V_Tumor*V_Tumor_v - (Q_Tumor-L_Tumor)*C_V_Tumor)/V_Tumor_v;
dxdt_K1 = (1/TAU_KILL)*(Kkill - K1);
dxdt_K2 = (1/TAU_KILL)*(K1 - K2);
dxdt_K3 = (1/TAU_KILL)*(K2 - K3);
dxdt_K4 = (1/TAU_KILL)*(K3 - K4);
dxdt_TE = KON*((A_E_Tumor /V_Tumor_e)*DENSITY_CAR - TE)*(TARGETCELL*DENSITY_TAA - TE) - KOFF*TE;
dxdt_A_E_Tumor = J_Tumor*C_V_Tumor*V_Tumor_v - L_Tumor*(A_E_Tumor/V_Tumor_e - TE/DENSITY_CAR) + Kact_CART * A_E_Tumor;
dxdt_V_Tumor = KG_EXP_TUMOR * V_Tumor - K4 * V_Tumor;

$TABLE
V_Tumor_v = 0.113* V_Tumor;
V_Tumor_e = 0.887* V_Tumor;
CplxPCART = TE * V_Tumor_e / A_E_Tumor;
CplxPT = TE / TARGETCELL;
Kact_CART = KEXP_CART_MAX * pow(CplxPT, GAMMA_ACT) / (pow(CplxPT, GAMMA_ACT) + pow(EC50, GAMMA_ACT));
Kkill = KKILL_MAX * pow(CplxPT, GAMMA_KILL) / (pow(CplxPT, GAMMA_KILL) + pow(IC50, GAMMA_KILL));
double TumorVolume = V_Tumor > 0 ? V_Tumor * 1000 : 0;   // mm3
double CARTblood = C_Blood / 1000;                       // cells per uL
double CARTtumor = A_E_Tumor / V_Tumor_e;                // cells per mL of tumour

$CAPTURE TumorVolume CARTblood CARTtumor CplxPT CplxPCART Kkill Kact_CART
