$PROB
Rifampicin -> glibenclamide: OATP inhibition plus CYP2C9/3A induction

// Asaumi R, Toshimoto K, Tobe Y, et al. Comprehensive PBPK model of
// rifampicin for quantitative prediction of complex drug-drug
// interactions: CYP3A/2C9 induction and OATP inhibition effects.
// CPT Pharmacometrics Syst Pharmacol 2018;7:186-196 (open access).
//
// Generated by tools/build_glibenclamide_ddi.py. Glibenclamide is
// transcribed from the glibenclamide model code in the article's
// Supplementary Text, with values from Supplementary Tables S1-S2, Table 1
// (beta = 0.2 column) and the OATP inhibition constant quoted in the
// Results (Ki,u 0.226 uM, from Yoshikado et al. 2016).
//
// Glibenclamide enters hepatocytes by OATP (saturable in rifampicin's
// case; for glibenclamide linear, inhibited by unbound rifampicin in the
// same liver zone) and by passive diffusion, and is metabolised by CYP2C9
// and CYP3A. Rifampicin does two opposite things: acutely it blocks uptake
// (exposure up); over days it induces CYP2C9/3A (exposure down). The
// rifampicin part is the same as models/ddi_rifampicin_midazolam.cpp, with
// CYP2C9 induction added.
//
// Concentrations are total blood concentrations in mg/L; gut lumen states
// are amounts (mg). Time in hours. IV doses go into the blood
// concentration state (divide mg by the blood volume).

$PARAM @annotated
BW          : 70      : Body weight (kg)

// physiology (Table S1), per kg
Qh_kg       : 1.24    : Hepatic blood flow (L/h/kg)
Qm_kg       : 0.642   : Muscle blood flow (L/h/kg)
Qs_kg       : 0.257   : Skin blood flow (L/h/kg)
Qa_kg       : 0.223   : Adipose blood flow (L/h/kg)
Qser_kg     : 0.274   : Serosal blood flow (L/h/kg)
Qvilli_kg   : 0.257   : Villous (mucosal) blood flow (L/h/kg)
Qpv_kg      : 0.531   : Portal vein blood flow (L/h/kg)
Vb_kg       : 0.0743  : Blood volume (L/kg)
Vh_kg       : 0.0174  : Hepatocyte volume (L/kg)
Vi_kg       : 0.0067  : Hepatic extracellular volume (L/kg)
Vm_kg       : 0.429   : Muscle volume (L/kg)
Vs_kg       : 0.111   : Skin volume (L/kg)
Va_kg       : 0.143   : Adipose volume (L/kg)
Vser_kg     : 0.00893 : Serosa volume (L/kg)
Vmucb_kg    : 0.00099 : Mucosal blood volume (L/kg)
Vent_kg     : 0.00739 : Enterocyte volume (L/kg)
Vpv_kg      : 0.001   : Portal vein volume (L/kg)

// enzyme turnover (Table S1)
kdeg3Ah     : 0.0158  : CYP3A degradation, hepatocytes (1/h)
kdeg3Ag     : 0.0288  : CYP3A degradation, enterocytes (1/h)
kdegUGTh    : 0.0158  : UGT degradation, hepatocytes (1/h)
kdegUGTg    : 0.0288  : UGT degradation, enterocytes (1/h)
kdeg2C9h    : 0.00666 : CYP2C9 degradation, hepatocytes (1/h)

// rifampicin (Table S2; optimised values from Table 1)
KaRif       : 37.6    : Absorption rate (1/h) [Table 1]
FaRif       : 1       : Fraction absorbed
FgRif       : 0.943   : Intestinal availability
fbRif       : 0.0778  : Unbound fraction in blood
fhRif       : 0.0814  : Unbound fraction in hepatocytes
fgRif       : 0.115   : Unbound fraction in enterocytes (fE)
KpScaleRif  : 6.65    : Scaling factor on in-silico Kp [Table 1]
KpmRif      : 0.0947  : Kp muscle
KpsRif      : 0.326   : Kp skin
KpaRif      : 0.0629  : Kp adipose
KpserRif    : 0.200   : Kp serosa
fbCLintall_kg : 0.251 : fB x overall hepatic intrinsic clearance (L/h/kg) [Table 1]
RdifRif     : 0.129   : PSdif,inf / PSact,inf
betaRif     : 0.5     : CLint,all / (PSact,inf + PSdif,inf) (0.2, 0.5 or 0.8 in the paper)
gammaRif    : 0.778   : PSdif,inf / PSdif,eff
KmuOATP     : 0.146   : Unbound Km for OATP uptake (ug/mL) [Table 1]
PSdifent_kg : 0.161   : Enterocyte basolateral diffusion clearance (L/h/kg) [Table 1]
CLr_kg      : 0.011   : Renal clearance (L/h/kg)
fmUGTh      : 0.759   : Fraction metabolised by UGT, liver
fmUGTg      : 0.759   : Fraction metabolised by UGT, gut
EC50u       : 0.0526  : Unbound EC50 for induction (ug/mL) [Table 1]
EmaxUGT     : 1.34    : Emax, UGT auto-induction [Table 1]
Emax3A      : 4.57    : Emax, CYP3A induction [Table 1]
Emax2C9     : 2.41    : Emax, CYP2C9 induction [Table 1]
KiuOATP     : 0.186   : Unbound Ki of rifampicin for OATP uptake (ug/mL; 0.226 uM)

// glibenclamide (Table S2; optimised values from Table 1, beta = 0.2)
KaGlb       : 0.445   : Absorption rate (1/h) [Table 1]
FaGlb       : 1       : Fraction absorbed
fbGlb       : 0.000774 : Unbound fraction in blood
fhGlb       : 0.0221  : Unbound fraction in hepatocytes
KpSFGlb     : 0.568   : Scaling factor on in-silico Kp [Table 1, beta 0.2]
KpmGlb      : 0.104   : Kp muscle
KpsGlb      : 0.447   : Kp skin
KpaGlb      : 0.0795  : Kp adipose
fbCLintallGlb_kg : 0.123 : fB x overall hepatic intrinsic clearance (L/h/kg) [Table 1]
RdifGlb     : 0.246   : PSdif,inf / PSact,inf
betaGlb     : 0.2     : CLint,all / (PSact,inf + PSdif,inf) (the paper's preferred value)
gammaGlb    : 0.24    : PSdif,inf / PSdif,eff
fmh2C9Glb   : 0.85    : Fraction metabolised by CYP2C9, liver (with beta 0.2)
fmh3AGlb    : 0.15    : Fraction metabolised by CYP3A, liver (with beta 0.2)
fmg3AGlb    : 1       : Fraction metabolised by CYP3A, gut
fgCLintgGlb_kg : 0.0131 : fE x enterocyte intrinsic clearance (L/h/kg)
CLpermGlb_kg : 0.103  : Gut permeability clearance, Qgut model (L/h/kg)
CLrGlb_kg   : 0       : Renal clearance (L/h/kg)

$CMT @annotated
GLB_CENT  : Glibenclamide blood (mg/L)
GLB_HE1   : Glibenclamide hepatic extracellular 1 (mg/L)
GLB_HC1   : Glibenclamide hepatocytes 1 (mg/L)
GLB_HE2   : Glibenclamide hepatic extracellular 2 (mg/L)
GLB_HC2   : Glibenclamide hepatocytes 2 (mg/L)
GLB_HE3   : Glibenclamide hepatic extracellular 3 (mg/L)
GLB_HC3   : Glibenclamide hepatocytes 3 (mg/L)
GLB_HE4   : Glibenclamide hepatic extracellular 4 (mg/L)
GLB_HC4   : Glibenclamide hepatocytes 4 (mg/L)
GLB_HE5   : Glibenclamide hepatic extracellular 5 (mg/L)
GLB_HC5   : Glibenclamide hepatocytes 5 (mg/L)
GLB_MUS   : Glibenclamide muscle (mg/L)
GLB_SKIN  : Glibenclamide skin (mg/L)
GLB_ADI   : Glibenclamide adipose (mg/L)
GLB_PV    : Glibenclamide portal vein (mg/L)
GLB_GUT   : Glibenclamide gut lumen (mg)
RIF_CENT  : Rifampicin blood (mg/L)
RIF_HE1   : Rifampicin hepatic extracellular 1 (mg/L)
RIF_HC1   : Rifampicin hepatocytes 1 (mg/L)
RIF_HE2   : Rifampicin hepatic extracellular 2 (mg/L)
RIF_HC2   : Rifampicin hepatocytes 2 (mg/L)
RIF_HE3   : Rifampicin hepatic extracellular 3 (mg/L)
RIF_HC3   : Rifampicin hepatocytes 3 (mg/L)
RIF_HE4   : Rifampicin hepatic extracellular 4 (mg/L)
RIF_HC4   : Rifampicin hepatocytes 4 (mg/L)
RIF_HE5   : Rifampicin hepatic extracellular 5 (mg/L)
RIF_HC5   : Rifampicin hepatocytes 5 (mg/L)
RIF_SER   : Rifampicin serosa (mg/L)
RIF_MUS   : Rifampicin muscle (mg/L)
RIF_SKIN  : Rifampicin skin (mg/L)
RIF_ADI   : Rifampicin adipose (mg/L)
RIF_LUMEN : Rifampicin gut lumen (mg)
RIF_ENT   : Rifampicin enterocytes (mg/L)
RIF_MUCB  : Rifampicin mucosal blood (mg/L)
UGT_H1    : UGT activity ratio, hepatocytes 1
UGT_H2    : UGT activity ratio, hepatocytes 2
UGT_H3    : UGT activity ratio, hepatocytes 3
UGT_H4    : UGT activity ratio, hepatocytes 4
UGT_H5    : UGT activity ratio, hepatocytes 5
UGT_G     : UGT activity ratio, enterocytes
CYP3A_H1  : CYP3A activity ratio, hepatocytes 1
CYP3A_H2  : CYP3A activity ratio, hepatocytes 2
CYP3A_H3  : CYP3A activity ratio, hepatocytes 3
CYP3A_H4  : CYP3A activity ratio, hepatocytes 4
CYP3A_H5  : CYP3A activity ratio, hepatocytes 5
CYP3A_G   : CYP3A activity ratio, enterocytes
CYP2C9_H1  : CYP2C9 activity ratio, hepatocytes 1
CYP2C9_H2  : CYP2C9 activity ratio, hepatocytes 2
CYP2C9_H3  : CYP2C9 activity ratio, hepatocytes 3
CYP2C9_H4  : CYP2C9 activity ratio, hepatocytes 4
CYP2C9_H5  : CYP2C9 activity ratio, hepatocytes 5

$MAIN
double Qh = Qh_kg * BW;
double Qm = Qm_kg * BW;
double Qs = Qs_kg * BW;
double Qa = Qa_kg * BW;
double Qser = Qser_kg * BW;
double Qvilli = Qvilli_kg * BW;
double Qhart = Qh - Qser - Qvilli;
double Qpv = Qpv_kg * BW;
double VbRif = Vb_kg * BW;
double Vh = Vh_kg * BW;
double Vi = Vi_kg * BW;
double Vm = Vm_kg * BW;
double Vs = Vs_kg * BW;
double Va = Va_kg * BW;
double Vser = Vser_kg * BW;
double Vmucb = Vmucb_kg * BW;
double Vent = Vent_kg * BW;
double Vpv = Vpv_kg * BW;

// rifampicin hepatic clearances from the hybrid parameters
double CLintallRif = fbCLintall_kg * BW / fbRif;
double VmaxOATP = 1.0 / (1 + RdifRif) * CLintallRif / betaRif * KmuOATP;
double PSdifinf = RdifRif / (1 + RdifRif) * CLintallRif / betaRif;
double PSdifeff = RdifRif / (1 + RdifRif) * CLintallRif / betaRif / gammaRif;
double CLintRif = RdifRif / (1 + RdifRif) * CLintallRif / (1 - betaRif) / gammaRif;
double PSdifent = PSdifent_kg * BW;
double QgutRif = fgRif * PSdifent * Qvilli / (Qvilli + fbRif * PSdifent);
double CLmetgRif = (QgutRif * (1.0 / FgRif - 1) - (1 - FaRif) * fgRif * PSdifent * 20) / fgRif;
double CLrRif = CLr_kg * BW;

double VbGlb = Vb_kg * BW;
double CLintallGlb = fbCLintallGlb_kg * BW / fbGlb;
double PSactinfGlb = 1.0 / (1 + RdifGlb) * CLintallGlb / betaGlb;
double PSdifinfGlb = RdifGlb / (1 + RdifGlb) * CLintallGlb / betaGlb;
double PSdifeffGlb = RdifGlb / (1 + RdifGlb) * CLintallGlb / betaGlb / gammaGlb;
double CLinthGlb = RdifGlb / (1 + RdifGlb) * CLintallGlb / (1 - betaGlb) / gammaGlb;
double CLpermGlb = CLpermGlb_kg * BW;
double QgutGlb = Qvilli * CLpermGlb / (Qvilli + CLpermGlb);
double fgCLintgGlb = fgCLintgGlb_kg * BW;
double CLrGlb = CLrGlb_kg * BW;

UGT_H1_0 = 1; UGT_H2_0 = 1; UGT_H3_0 = 1; UGT_H4_0 = 1; UGT_H5_0 = 1; UGT_G_0 = 1;
CYP3A_H1_0 = 1; CYP3A_H2_0 = 1; CYP3A_H3_0 = 1; CYP3A_H4_0 = 1; CYP3A_H5_0 = 1; CYP3A_G_0 = 1;
CYP2C9_H1_0 = 1; CYP2C9_H2_0 = 1; CYP2C9_H3_0 = 1; CYP2C9_H4_0 = 1; CYP2C9_H5_0 = 1;

$ODE
// ---- glibenclamide: OATP uptake competitively inhibited by unbound rifampicin ----
double UPG1 = fbGlb * (PSactinfGlb / (1 + fbRif * RIF_HE1 / KiuOATP) + PSdifinfGlb) * GLB_HE1;
double UPG2 = fbGlb * (PSactinfGlb / (1 + fbRif * RIF_HE2 / KiuOATP) + PSdifinfGlb) * GLB_HE2;
double UPG3 = fbGlb * (PSactinfGlb / (1 + fbRif * RIF_HE3 / KiuOATP) + PSdifinfGlb) * GLB_HE3;
double UPG4 = fbGlb * (PSactinfGlb / (1 + fbRif * RIF_HE4 / KiuOATP) + PSdifinfGlb) * GLB_HE4;
double UPG5 = fbGlb * (PSactinfGlb / (1 + fbRif * RIF_HE5 / KiuOATP) + PSdifinfGlb) * GLB_HE5;
dxdt_GLB_CENT = 1.0 / VbGlb * (Qh * GLB_HE5 - (Qh - Qpv) * GLB_CENT - Qpv * GLB_CENT +
    Qm * (GLB_MUS / (KpSFGlb * KpmGlb) - GLB_CENT) + Qs * (GLB_SKIN / (KpSFGlb * KpsGlb) - GLB_CENT) +
    Qa * (GLB_ADI / (KpSFGlb * KpaGlb) - GLB_CENT) - CLrGlb * GLB_CENT);
dxdt_GLB_HE1 = 5.0 / Vi * ((Qh - Qpv) * GLB_CENT + Qpv * GLB_PV - Qh * GLB_HE1 + (fhGlb * PSdifeffGlb * GLB_HC1 - UPG1) / 5);
dxdt_GLB_HC1 = 5.0 / Vh * (UPG1 - fhGlb * PSdifeffGlb * GLB_HC1 - fhGlb * CLinthGlb * (1 + fmh3AGlb * (CYP3A_H1 - 1) + fmh2C9Glb * (CYP2C9_H1 - 1)) * GLB_HC1) / 5;
dxdt_GLB_HE2 = 5.0 / Vi * (Qh * (GLB_HE1 - GLB_HE2) + (fhGlb * PSdifeffGlb * GLB_HC2 - UPG2) / 5);
dxdt_GLB_HC2 = 5.0 / Vh * (UPG2 - fhGlb * PSdifeffGlb * GLB_HC2 - fhGlb * CLinthGlb * (1 + fmh3AGlb * (CYP3A_H2 - 1) + fmh2C9Glb * (CYP2C9_H2 - 1)) * GLB_HC2) / 5;
dxdt_GLB_HE3 = 5.0 / Vi * (Qh * (GLB_HE2 - GLB_HE3) + (fhGlb * PSdifeffGlb * GLB_HC3 - UPG3) / 5);
dxdt_GLB_HC3 = 5.0 / Vh * (UPG3 - fhGlb * PSdifeffGlb * GLB_HC3 - fhGlb * CLinthGlb * (1 + fmh3AGlb * (CYP3A_H3 - 1) + fmh2C9Glb * (CYP2C9_H3 - 1)) * GLB_HC3) / 5;
dxdt_GLB_HE4 = 5.0 / Vi * (Qh * (GLB_HE3 - GLB_HE4) + (fhGlb * PSdifeffGlb * GLB_HC4 - UPG4) / 5);
dxdt_GLB_HC4 = 5.0 / Vh * (UPG4 - fhGlb * PSdifeffGlb * GLB_HC4 - fhGlb * CLinthGlb * (1 + fmh3AGlb * (CYP3A_H4 - 1) + fmh2C9Glb * (CYP2C9_H4 - 1)) * GLB_HC4) / 5;
dxdt_GLB_HE5 = 5.0 / Vi * (Qh * (GLB_HE4 - GLB_HE5) + (fhGlb * PSdifeffGlb * GLB_HC5 - UPG5) / 5);
dxdt_GLB_HC5 = 5.0 / Vh * (UPG5 - fhGlb * PSdifeffGlb * GLB_HC5 - fhGlb * CLinthGlb * (1 + fmh3AGlb * (CYP3A_H5 - 1) + fmh2C9Glb * (CYP2C9_H5 - 1)) * GLB_HC5) / 5;
dxdt_GLB_MUS = 1.0 / Vm * Qm * (GLB_CENT - GLB_MUS / (KpSFGlb * KpmGlb));
dxdt_GLB_SKIN = 1.0 / Vs * Qs * (GLB_CENT - GLB_SKIN / (KpSFGlb * KpsGlb));
dxdt_GLB_ADI = 1.0 / Va * Qa * (GLB_CENT - GLB_ADI / (KpSFGlb * KpaGlb));
dxdt_GLB_PV = 1.0 / Vpv * (Qpv * (GLB_CENT - GLB_PV) +
    KaGlb * QgutGlb / (QgutGlb + fgCLintgGlb * (1 + fmg3AGlb * (CYP3A_G - 1))) * GLB_GUT);
dxdt_GLB_GUT = -KaGlb / FaGlb * GLB_GUT;

// ---- rifampicin ----
double UP1 = fbRif * (VmaxOATP / (KmuOATP + fbRif * RIF_HE1) + PSdifinf) * RIF_HE1;
double UP2 = fbRif * (VmaxOATP / (KmuOATP + fbRif * RIF_HE2) + PSdifinf) * RIF_HE2;
double UP3 = fbRif * (VmaxOATP / (KmuOATP + fbRif * RIF_HE3) + PSdifinf) * RIF_HE3;
double UP4 = fbRif * (VmaxOATP / (KmuOATP + fbRif * RIF_HE4) + PSdifinf) * RIF_HE4;
double UP5 = fbRif * (VmaxOATP / (KmuOATP + fbRif * RIF_HE5) + PSdifinf) * RIF_HE5;

dxdt_RIF_CENT = 1.0 / VbRif * (Qh * RIF_HE5 + Qm * (RIF_MUS / (KpScaleRif * KpmRif) - RIF_CENT) +
    Qs * (RIF_SKIN / (KpScaleRif * KpsRif) - RIF_CENT) + Qa * (RIF_ADI / (KpScaleRif * KpaRif) - RIF_CENT) -
    (Qhart + Qser + Qvilli) * RIF_CENT - CLrRif * RIF_CENT);
dxdt_RIF_HE1 = 5.0 / Vi * (Qhart * RIF_CENT + Qvilli * RIF_MUCB + Qser * RIF_SER / (KpScaleRif * KpserRif) -
    Qh * RIF_HE1 + (fhRif * PSdifeff * RIF_HC1 - UP1) / 5);
dxdt_RIF_HC1 = 5.0 / Vh * (UP1 - fhRif * PSdifeff * RIF_HC1 - fhRif * CLintRif * (1 + fmUGTh * (UGT_H1 - 1)) * RIF_HC1) / 5;
dxdt_RIF_HE2 = 5.0 / Vi * (Qh * (RIF_HE1 - RIF_HE2) + (fhRif * PSdifeff * RIF_HC2 - UP2) / 5);
dxdt_RIF_HC2 = 5.0 / Vh * (UP2 - fhRif * PSdifeff * RIF_HC2 - fhRif * CLintRif * (1 + fmUGTh * (UGT_H2 - 1)) * RIF_HC2) / 5;
dxdt_RIF_HE3 = 5.0 / Vi * (Qh * (RIF_HE2 - RIF_HE3) + (fhRif * PSdifeff * RIF_HC3 - UP3) / 5);
dxdt_RIF_HC3 = 5.0 / Vh * (UP3 - fhRif * PSdifeff * RIF_HC3 - fhRif * CLintRif * (1 + fmUGTh * (UGT_H3 - 1)) * RIF_HC3) / 5;
dxdt_RIF_HE4 = 5.0 / Vi * (Qh * (RIF_HE3 - RIF_HE4) + (fhRif * PSdifeff * RIF_HC4 - UP4) / 5);
dxdt_RIF_HC4 = 5.0 / Vh * (UP4 - fhRif * PSdifeff * RIF_HC4 - fhRif * CLintRif * (1 + fmUGTh * (UGT_H4 - 1)) * RIF_HC4) / 5;
dxdt_RIF_HE5 = 5.0 / Vi * (Qh * (RIF_HE4 - RIF_HE5) + (fhRif * PSdifeff * RIF_HC5 - UP5) / 5);
dxdt_RIF_HC5 = 5.0 / Vh * (UP5 - fhRif * PSdifeff * RIF_HC5 - fhRif * CLintRif * (1 + fmUGTh * (UGT_H5 - 1)) * RIF_HC5) / 5;
dxdt_RIF_SER = 1.0 / Vser * Qser * (RIF_CENT - RIF_SER / (KpScaleRif * KpserRif));
dxdt_RIF_MUS = 1.0 / Vm * Qm * (RIF_CENT - RIF_MUS / (KpScaleRif * KpmRif));
dxdt_RIF_SKIN = 1.0 / Vs * Qs * (RIF_CENT - RIF_SKIN / (KpScaleRif * KpsRif));
dxdt_RIF_ADI = 1.0 / Va * Qa * (RIF_CENT - RIF_ADI / (KpScaleRif * KpaRif));
dxdt_RIF_LUMEN = -KaRif / FaRif * RIF_LUMEN + fgRif * PSdifent * 20 * RIF_ENT;
dxdt_RIF_ENT = 1.0 / Vent * (KaRif * RIF_LUMEN + fbRif * PSdifent * RIF_MUCB -
    fgRif * (PSdifent * 21 + CLmetgRif * (1 + fmUGTg * (UGT_G - 1))) * RIF_ENT);
dxdt_RIF_MUCB = 1.0 / Vmucb * (Qvilli * (RIF_CENT - RIF_MUCB) + fgRif * PSdifent * RIF_ENT - fbRif * PSdifent * RIF_MUCB);

// ---- enzyme induction by unbound rifampicin ----
double IH1 = fhRif * RIF_HC1 / (fhRif * RIF_HC1 + EC50u);
double IH2 = fhRif * RIF_HC2 / (fhRif * RIF_HC2 + EC50u);
double IH3 = fhRif * RIF_HC3 / (fhRif * RIF_HC3 + EC50u);
double IH4 = fhRif * RIF_HC4 / (fhRif * RIF_HC4 + EC50u);
double IH5 = fhRif * RIF_HC5 / (fhRif * RIF_HC5 + EC50u);
double IG  = fgRif * RIF_ENT / (fgRif * RIF_ENT + EC50u);
dxdt_UGT_H1 = kdegUGTh * (1 + EmaxUGT * IH1 - UGT_H1);
dxdt_UGT_H2 = kdegUGTh * (1 + EmaxUGT * IH2 - UGT_H2);
dxdt_UGT_H3 = kdegUGTh * (1 + EmaxUGT * IH3 - UGT_H3);
dxdt_UGT_H4 = kdegUGTh * (1 + EmaxUGT * IH4 - UGT_H4);
dxdt_UGT_H5 = kdegUGTh * (1 + EmaxUGT * IH5 - UGT_H5);
dxdt_UGT_G  = kdegUGTg * (1 + EmaxUGT * IG - UGT_G);
dxdt_CYP3A_H1 = kdeg3Ah * (1 + Emax3A * IH1 - CYP3A_H1);
dxdt_CYP3A_H2 = kdeg3Ah * (1 + Emax3A * IH2 - CYP3A_H2);
dxdt_CYP3A_H3 = kdeg3Ah * (1 + Emax3A * IH3 - CYP3A_H3);
dxdt_CYP3A_H4 = kdeg3Ah * (1 + Emax3A * IH4 - CYP3A_H4);
dxdt_CYP3A_H5 = kdeg3Ah * (1 + Emax3A * IH5 - CYP3A_H5);
dxdt_CYP3A_G  = kdeg3Ag * (1 + Emax3A * IG - CYP3A_G);
dxdt_CYP2C9_H1 = kdeg2C9h * (1 + Emax2C9 * IH1 - CYP2C9_H1);
dxdt_CYP2C9_H2 = kdeg2C9h * (1 + Emax2C9 * IH2 - CYP2C9_H2);
dxdt_CYP2C9_H3 = kdeg2C9h * (1 + Emax2C9 * IH3 - CYP2C9_H3);
dxdt_CYP2C9_H4 = kdeg2C9h * (1 + Emax2C9 * IH4 - CYP2C9_H4);
dxdt_CYP2C9_H5 = kdeg2C9h * (1 + Emax2C9 * IH5 - CYP2C9_H5);

$TABLE
double GLB = GLB_CENT * 1000;       // glibenclamide blood (ng/mL)
double RIF = RIF_CENT;              // rifampicin blood (ug/mL)
double CYP3A_LIVER = (CYP3A_H1 + CYP3A_H2 + CYP3A_H3 + CYP3A_H4 + CYP3A_H5) / 5;
double CYP2C9_LIVER = (CYP2C9_H1 + CYP2C9_H2 + CYP2C9_H3 + CYP2C9_H4 + CYP2C9_H5) / 5;
double OATP_ACTIVITY = 1.0 / (1 + fbRif * RIF_HE1 / KiuOATP);

$CAPTURE GLB RIF CYP3A_LIVER CYP2C9_LIVER OATP_ACTIVITY
